### ISSUE TITLE
Exception when loading an Alt app

### ISSUE THREAD

**Issue by Shearerbeard** [goatslacker/alt-devtool#10]
alts.all(...).map is not a function

Loading app while running this tool throws the above exception. I rebuilt the chrome package manually and it seems to fix the issue so I'm guessing the dist just needs to be repackaged with your recent updates. 

alt 0.16.8
OSX 10.10.3
Chrome 43

**Comment by goatslacker** [comment]
I need to update the dist, yes

**Comment by Shearerbeard** [comment]
Any movement on this? I've got a manual build working for me on a local branch - I ran the build-background script but it threw an error due to a redeclaration of a let value in a switch statement in registerAlt.js. After correcting this the tool seems to be working great.

**Comment by goatslacker** [comment]
Updated crx.

**Comment by Shearerbeard** [comment]
Thanks much! I can confirm its working great.
