### ISSUE TITLE
chrome disables Alt-devtools .

### ISSUE THREAD

**Issue by tonis2** [goatslacker/alt-devtool#12]
Chrome has some kind of new policy that disallows apps not found on store, so it disables alt-devtool also. And i cant find it in chrome shop.

**Comment by goatslacker** [comment]
I haven't paid the 5$ yet to put it in the chrome store. You can load in your own crx though. Tested on Chrome 43.

**Comment by tonis2** [comment]
Yes extracted the crx file, then installed from chrome developer mode, and its working.
