### ISSUE TITLE
Provide Chrome store URL in the README

### ISSUE THREAD

**Issue by mathieumg** [goatslacker/alt-devtool#13]
From the readme:

> If you'd like to install this yourself without going through the chrome store then visit this link:

And if I want to go through the Chrome store? Even some googling and searching in the Chrome store didn't help.

Thanks!

**Comment by goatslacker** [comment]
Ah let me remove that bit.

**Comment by dmitry** [comment]
@mathieumg same story here. BTW debugger looks great!

**Comment by goatslacker** [comment]
3b1c738d2ce1edfaad5101afcc82515285d05a46
