### ISSUE TITLE
Uncaught TypeError: CSV.parseCSV is not a symbol

### ISSUE THREAD

**Issue by esamattis** [goatslacker/alt-devtool#15]
Just tried Alt and alt-devtool for the first time and got the following the error in the title.

I guess it's because Alt got rid of Symbols in 0.17.0

https://github.com/goatslacker/alt/blob/master/CHANGELOG.md#0170

The only reference on Symbols in alt-devtool can be found here

https://github.com/goatslacker/alt-devtool/blob/c25c63cd8a953e8387b08b188843d5e9e9ab8838/src/test.js#L40

**Comment by goatslacker** [comment]
Updating the new crx now.

**Comment by goatslacker** [comment]
81d8d196228a859a6f9b24995a6667e470bd52d5

**Comment by goatslacker** [comment]
Redownload/install the new crx into chrome and that error will go away. :fireworks:
