### ISSUE TITLE
Not from Chrome Web Store

### ISSUE THREAD

**Issue by ktmn** [goatslacker/alt-devtool#19]
Might be issue with Chrome itself, not this extension, but when I drag the .crx to the chrome://extensions tab it installs it and a second later disables it saying "Not from Chrome Web Store.". So I check the "Enable" box again and nothing happens. Instead, in console, it writes error:

```
Unchecked runtime.lastError while running management.setEnabled: Extension hlphpmkmonogpcpobpgjoidchbgbplio cannot be modified by user.
```

I'm on Windows 10, ran the Chrome as Administrator. 
Tried enabling the extension in Developer mode and without, same error.

The way I got it working was to rename the extension to .zip, unpack, and load it as unpacked extension in Developer mode. But I'm still posting the issue just in case, cause your readme says it should work by drag and dropping.

**Comment by harriha** [comment]
Yeah, noticed the same, the installation is quite cumbersome on Windows at least, and soon maybe also on other OS's (if not already?) according to this at least https://blog.chromium.org/2015/05/continuing-to-protect-chrome-users-from.html . 

Would be great to see this dev tool in Chrome Web Store for easier use :+1:

**Comment by natecox** [comment]
Seems like a solid tool. Why isn't it already on the chrome store? I know that there are already inspectors for Ember and React there.

**Comment by goatslacker** [comment]
Haven't ponied up the 5$ to get it on the store. I figured it was easy enough to install that it didn't need to be in the store but if people are having trouble then I'll add it in.

**Comment by AlbanMinassian** [comment]
Same error : alt-devtool disable because not in Chrome Web Store.

But we can enabled alt-devtool if we install the new extension "Chrome Apps & Extensions Developer Tool" 'https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc)

Thank for this extension 
Ami44

**Comment by AlbanMinassian** [comment]
Not work, after two days, alt-devtool is force to "disabled"

**Comment by AlbanMinassian** [comment]
Solution : download github source and apply steps like https://github.com/crysislinux/smart_websocket_client

**Comment by goatslacker** [comment]
Just published to Chrome Web Store. Not sure when it'll be available but here's the possible URL where it'll be at: https://chrome.google.com/webstore/detail/goatslacker/jfjefoacbhfenehankalijibcccajchg

**Comment by AlbanMinassian** [comment]
Thanks
