### ISSUE TITLE
Failure with createStore()

### ISSUE THREAD

**Issue by jareware** [goatslacker/alt-devtool#20]
If I define a store like:

```
import immutable from 'alt/utils/ImmutableUtil';

alt.createStore(immutable({
  displayName: 'derpStore',
  state: new Immutable.Map({
    count: 0
  }),
  reduce: (state, payload) => {
    return state.updateIn([ 'count' ], x => x + 1);
  }
}));
```

I get:

```
TypeError: Cannot read property 'onSerialize' of undefined
```

from [here](https://github.com/goatslacker/alt-devtool/blob/master/scripts/utils/registerAlt.js#L105).

If I use `alt.addStore(StoreClass)` with the same `config` patched into the prototype it works as expected. Also the immutable-util works as expected, because when I `takeSnapshot('derpStore')` I get a sensible serialization.

Ideas?

**Comment by jareware** [comment]
Well, actually it looks like [this config access](https://github.com/goatslacker/alt-devtool/blob/master/scripts/utils/registerAlt.js#L105-L106) should actually use `store.StoreModel.config` [like `snapshot()` does](https://github.com/goatslacker/alt/blob/master/src/alt/utils/StateFunctions.js#L27), and it sorta accidentally works with class-based stores because the `config` is available on the prototype chain.

**Comment by zerbons** [comment]
Also having this issue.

**Comment by jbroadice** [comment]
This is also happening when using [alt-router](https://github.com/altjs/router).

**Comment by goatslacker** [comment]
Fixed in alt@0.17.8.

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/commit/d72eb9d633e313bf1f3cdab546d2a3a17e762421

**Comment by jareware** [comment]
Very nice, thanks!
