### ISSUE TITLE
Better defined releases

### ISSUE THREAD

**Issue by jareware** [goatslacker/alt-devtool#23]
Having explicit instructions for building this extension would be nice! I've been thinking of a few neat features for the devtool, would help in contributing. Or, better yet, automate releases somehow.

Oh, and currently it's impossible to tell whether you're running an outdated version of the devtool, because there's a) no releases on GitHub, and b) no version number (that I know of at least) in the devtools UI.

Inspired by @chodorowicz's comment on #17.

**Comment by goatslacker** [comment]
Now that I've published on chrome's store I'll start using the manifest's version field for releases https://github.com/goatslacker/alt-devtool/blob/master/manifest.json

**Comment by goatslacker** [comment]
I'll also tag the releases here on github :)

**Comment by goatslacker** [comment]
Oh and I added instructions on how to build this yourself. https://github.com/goatslacker/alt-devtool#building-this-yourself

**Comment by jareware** [comment]
Oh wow, someone's being a model citizen. <3

Thanks a lot!

**Comment by chodorowicz** [comment]
Great! Thanks!
