### ISSUE TITLE
Does not seem to work?

### ISSUE THREAD

**Issue by winkler1** [goatslacker/alt-devtool#3]
Was able to do "window["alt.js.org"] = alt;' and get the snapshot button to work... but none of the dispatch logging seems to fire. Seems pretty useful if it did :)

**Comment by goatslacker** [comment]
It's missing some css. I'll be repacking soon with the added css.

**Comment by kiia** [comment]
For me the dispatch logging is not working either, but the snapshot button works. In the stores tab the stores get their initial values, but do not get updated. 
With Windows 8, Chrome Version 43.0.2357.73 beta-m (64-bit) and alt 0.16.6 the console logs:

Uncaught TypeError: alt.createUnsavedStore is not a function
makeFinalStore @ altif.js:48

**Comment by goatslacker** [comment]
@winkler1 I've added the css, try the new url. Don't download from cdn since it has the cached version which is old.

@kiia is the extension you have the same one that's currently in the repo?

**Comment by kiia** [comment]
I used this link from the wiki https://github.com/goatslacker/alt-devtool/raw/master/dist/alt-dev.crx

**Comment by goatslacker** [comment]
@kiia I think I may know why it's not working (alt is undefined in your case), first I have to figure out why it's working for me and I can't repro.

**Comment by kiia** [comment]
Mhh, I can't reproduce it anymore either, it started just working! The only difference is the app I've been working on and a Windows restart in between.

**Comment by goatslacker** [comment]
oh ok a Windows restart, I should add that to the docs :)

**Comment by goatslacker** [comment]
Updated crx.
